version: "3"

services:
  app:
    build:
     context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - .db-data:/var/lib/postgresql/data
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASS=katana111
    depends_on:
    - db

  db:
    image: postgres:10-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=katana111
