# Generated by Django 2.2.1 on 2019-05-28 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewslot',
            old_name='interview_time',
            new_name='interview_end_time',
        ),
        migrations.AddField(
            model_name='interviewslot',
            name='interview_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
